<div class="m-20">
   <form action="/login" class="space-y-4" method="POST">
      <div>
         <label for="artwork_title" class="text-2xl font-bold block mb-1">Titulo da arte</label>
         <input
            id="artwork_title"
            name="artwork[title]"
            class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500"
            type="text"
            placeholder="Titulo da arte" 
            require/>
      </div>

      <div>
         <label for="artwork_description" class="text-sm block mb-1">Descrição</label>
         <div class="relative">
            <textarea
               id="artwork_description"
               name="artwork[description]"
               type="text"
               rows='6'
               cols='50'
               class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500"
               placeholder="Descrição do projeto">
            </textarea>
         </div>
      </div>

      <div>
         <form action="/upload" method="post" enctype="multipart/form-data">
            <label for="imagem">Selecione uma imagem:</label><br>
            <input type="file" id="imagem" name="imagem" accept="image/*">
            <br><br>
            <button type="submit">Enviar</button>
         </form>
      </div>
      <button
         type="submit"
         class="w-full bg-orange-500 hover:bg-orange-600 text-white py-2 rounded-md font-semibold transition">
         Postar arte
      </button>
   </form>
</div>
