<form action="/login" class="space-y-4" method="POST">
   <div>
      <label for="user_email" class="text-sm block mb-1">E-mail</label>
      <input
         id="user_email"
         type="email"
         name="user[email]"
         class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500"
         placeholder="Enter your e-mail" />
   </div>
   <div>
      <label for="user_password" class="text-sm block mb-1">Password</label>
      <div class="relative">
         <input
            id="user_password"
            name="user[password]"
            type="password"
            class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            placeholder="Enter password" />
      </div>
   </div>
   <button
      type="submit"
      class="w-full bg-indigo-800 hover:bg-indigo-900 text-white py-2 rounded-md font-semibold transition">
      Login
   </button>
   <div class="text-center text-sm text-gray-500">Or</div>
   <button
      type="button"
      class="w-full border border-gray-300 py-2 rounded-md flex items-center justify-center gap-2 hover:bg-gray-100 transition">
      <img src="https://www.svgrepo.com/show/475656/google-color.svg" alt="Google" class="w-5 h-5" />
      Continue with Google
   </button>
   <p class="text-xs text-center text-gray-500 mt-4">
      By continuing, you agree to ArtHive
      <a href="#" class="text-blue-600 underline">Terms of Services</a>
      and
      <a href="#" class="text-blue-600 underline">Privacy Policy</a>.
   </p>
</form>