<div class="mb-8 min-h-screen max-w-screen-xl mx-auto">
    <div class="flex flex-col items-center p-5">
        <h1
            class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl">
            Sua arte merece ser vista e sentida
        </h1>
        <p
            class="mb-6 text-lg text-center font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48">
            Compartilhe, descubra e se conecte com artistas de todo o mundo. Uma galeria
            viva onde sua arte é valorizada e inspirada.
        </p>
        <a
            href="#"
            class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-white bg-orange-600 rounded-lg hover:bg-orange-800 focus:ring-4 focus:ring-orange-300">
            Saiba Mais
            <svg
                class="w-3.5 h-3.5 ms-2 rtl:rotate-180"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 14 10">
                <path
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M1 5h12m0 0L9 1m4 4L9 9" />
            </svg>
        </a>
    </div>

    <!-- ARTES PARA RENDERIZAR  -->
    <div class="flex flex-wrap justify-start itens-start gap-x-16 m-3 max-w-screen-xl mx-auto">
        <?php foreach ($paginator->registers() as $artwork) : ?>
            <div class="flex flex-col max-w-sm gap-3 mt-10  rounded-2xl shadow-lg">
                <div class="min-h-96 max-h-96 overflow-hidden rounded-2xl shadow-lg">
                    <img src="<?=$artwork->image()->path()?>" alt="arte"n
                        class="object-cover rounded-2xl w-full h-full transition-transform duration-300 ease-in-out hover:scale-105 hover:shadow-xl" />
                </div>

                <div class="flex flex-col p-3 gap-3 justify-between h-full">
                    <div>
                        <div class="flex flex-row justify-between">
                            <h1 class="mb-2 text-2xl font-bold tracking-tight text-gray-900"><?= $artwork->title?></h1>
                            <h2 class="mb-2 text-xl font-semibold text-gray-600"><?= $artwork->artist->user->name?></h2>
                        </div>
                        <span class="mb-3 font-normal text-gray-700"><?= $artwork->description ?></span>
                    </div>

                    <div class="flex justify-between">
                        <button
                            class="text-white bg-orange-700 hover:bg-orange-800 focus:ring-4 focus:ring-orange-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-orange-600 dark:hover:bg-orange-700 focus:outline-none dark:focus:ring-orange-800"
                            type="button"
                            data-drawer-target="drawer-contact"
                            data-drawer-show="drawer-contact"
                            aria-controls="drawer-contact">
                            Mais informações
                        </button>

                        <div class="flex -space-x-4 rtl:space-x-reverse">
                            <img
                                class="w-10 h-10 border-2 border-white rounded-full dark:border-gray-800"
                                src="<?= $friend ?>"
                                alt="" />
                            <img
                                class="w-10 h-10 border-2 border-white rounded-full dark:border-gray-800"
                                src="<?= $friend ?>"
                                alt="" />
                            <img
                                class="w-10 h-10 border-2 border-white rounded-full dark:border-gray-800"
                                src="<?= $friend ?>"
                                alt="" />
                            <div
                                class="flex items-center justify-center w-10 h-10 text-xs font-medium text-white bg-gray-700 border-2 border-white rounded-full hover:bg-gray-600 dark:border-gray-800"
                                href="#"><?= $folowers ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <div class="mt-2 flex flex-col justify-center items-start">
        <?php $paginator->renderPagesNavigation() ?>
    </div>
</div>