<div class="m-20">
   <form action="/upload" class="space-y-4" method="POST">
      <div>
         <label for="artwork_title" class="text-2xl font-bold block mb-1">Titulo da arte</label>
         <input
            id="artwork_title"
            name="artwork[title]"
            class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500"
            type="text"
            placeholder="Titulo da arte" 
            require/>
      </div>

      <div>
         
         <div class="relative">
            <label for="artwork_description" class="text-sm block mb-1"><?= $description ?></label>
            <textarea
               id="artwork_description"
               name="artwork[description]"
               type="text"
               rows='6'
               cols='50'
               class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500"
               placeholder='Descrição da arte'></textarea>
         </div>
      </div>

      <div class="flex flex-col">
         <label for="artwork_image"
         >Selecione uma imagem:</label>
         <input type="file" id="artwork_image" name="artwork[image]" accept="image/*" class="">
      </div>

      <button
         type="submit"
         class="w-full bg-orange-500 hover:bg-orange-600 text-white py-2 rounded-md font-semibold transition">
         Publicar arte
      </button>
   </form>
</div>
