<div class="p-12">
   <div class="div-title flex justify-between items-center max-w-screen-xl mx-auto">
      <div>
         <h1 class="text-3xl font-bold text-gray-900"> <?= $title ?> </h1>
         <h2 class="text-md text-gray-600"> <?= $subtitle?> </h2>
      </div>
      <div>
         <form action="<?= route('artwork.new') ?>" method="GET" class="inline flex items-center">
            <button type="submit"
               class="flex items-center gap-3 text-white bg-orange-500 hover:bg-orange-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-3 text-center sel-center">
               Publicar nova arte

               <svg xmlns="http://www.w3.org/2000/svg" 
                  viewBox="0 0 24 24" 
                  fill="currentColor"
                  class="size-6">
                  <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 9a.75.75 0 0 0-1.5 0v2.25H9a.75.75 0 0 0 0 1.5h2.25V15a.75.75 0 0 0 1.5 0v-2.25H15a.75.75 0 0 0 0-1.5h-2.25V9Z" clip-rule="evenodd" />
               </svg>

            </button>
         </form>
      </div>
   </div>
   <!-- ARTES PARA RENDERIZAR  -->
   <div class="flex flex-wrap justify-start gap-x-16 m-3 max-w-screen-xl mx-auto">
      <?php foreach ($artworks as $artwork) : ?>
         <div class="flex flex-col max-w-sm gap-3 mt-10 rounded-2xl shadow-lg">
            <!-- DIV PARA ARTE -->
            <div class="min-h-96 max-h-96 overflow-hidden rounded-2xl shadow-lg">
               <img src="/assets<?=$artwork->image_url?>" alt="arte"
                  class="object-cover rounded-2xl w-full h-full transition-transform duration-300 ease-in-out hover:scale-105 hover:shadow-xl"
               />
            </div>
            <div class="flex flex-col p-3 gap-3">
               <!-- DIV TITULOS DAS OBRAS -->
               <div>
                  <h1 class="text-xl font-bold text-gray-900"><?= $artwork->title ?></h1>
                  <span class="text-md text-gray-600"><?= $artwork->description ?></span>
               </div>
               <!-- DIV DOS BOTOES DE EDIT AND DELETE -->
               <div class="flex justify-between">
                  
                  <button type="button" data-modal-target="popup-modal-<?= $artwork->id ?>" data-modal-toggle="popup-modal-<?= $artwork->id ?>">
                     <svg xmlns="http://www.w3.org/2000/svg" 
                        viewBox="0 0 24 24" fill="currentColor" 
                        class="size-6 text-red-600">
                        <path fill-rule="evenodd" d="M16.5 4.478v.227a48.816 48.816 0 0 1 3.878.512.75.75 0 1 1-.256 1.478l-.209-.035-1.005 13.07a3 3 0 0 1-2.991 2.77H8.084a3 3 0 0 1-2.991-2.77L4.087 6.66l-.209.035a.75.75 0 0 1-.256-1.478A48.567 48.567 0 0 1 7.5 4.705v-.227c0-1.564 1.213-2.9 2.816-2.951a52.662 52.662 0 0 1 3.369 0c1.603.051 2.815 1.387 2.815 2.951Zm-6.136-1.452a51.196 51.196 0 0 1 3.273 0C14.39 3.05 15 3.684 15 4.478v.113a49.488 49.488 0 0 0-6 0v-.113c0-.794.609-1.428 1.364-1.452Zm-.355 5.945a.75.75 0 1 0-1.5.058l.347 9a.75.75 0 1 0 1.499-.058l-.346-9Zm5.48.058a.75.75 0 1 0-1.498-.058l-.347 9a.75.75 0 0 0 1.5.058l.345-9Z" clip-rule="evenodd" />
                     </svg>
                  </button>

                  <!-- INICIO MODAL PARA CONFIRMAR EXCLUSÃO  -->
                  <div id="popup-modal-<?= $artwork->id ?>" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                     <div class="relative p-4 w-full max-w-md max-h-full">
                        <div class="relative bg-white rounded-lg shadow-sm dark:bg-gray-700">
                              <button type="button" class="absolute top-3 end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="popup-modal">
                                 <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                                 </svg>
                                 <span class="sr-only">Close modal</span>
                              </button>
                              <div class="p-4 md:p-5 text-center">
                                 <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                                 </svg>
                                 <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">Tem certeza que quer excluir?</h3>
                                 
                                 <form action="<?= route('artwork.destroy', ['id' => $artwork->id]) ?>" method="POST" id="<?=$artwork->id?>">
                                    <input type="hidden" name="_method" value="DELETE">

                                    <button type="submit" data-modal-hide="popup-modal-<?= $artwork->id ?>" class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center">
                                       Sim, tenho certeza
                                    </button>
                                 </form>
                                 
                                 <button data-modal-hide="popup-modal-<?= $artwork->id ?>" type="button" class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
                                    Não, cancelar
                                 </button>
                              </div>
                        </div>
                     </div>
                  </div>
                  <!-- FIM MODAL PARA CONFIRMAR EXCLUSÃO  -->
                  <!-- INICIO BUTTON PARA EDITAR  -->
                  <form action="<?= route('artwork.edit', ['id' => $artwork->id]) ?>" method="GET" id="<?=$artwork->id?>">
                     <button type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" 
                           viewBox="0 0 24 24" 
                           fill="currentColor" 
                           class="size-6">
                           <path d="M21.731 2.269a2.625 2.625 0 0 0-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 0 0 0-3.712ZM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 0 0-1.32 2.214l-.8 2.685a.75.75 0 0 0 .933.933l2.685-.8a5.25 5.25 0 0 0 2.214-1.32l8.4-8.4Z" />
                           <path d="M5.25 5.25a3 3 0 0 0-3 3v10.5a3 3 0 0 0 3 3h10.5a3 3 0 0 0 3-3V13.5a.75.75 0 0 0-1.5 0v5.25a1.5 1.5 0 0 1-1.5 1.5H5.25a1.5 1.5 0 0 1-1.5-1.5V8.25a1.5 1.5 0 0 1 1.5-1.5h5.25a.75.75 0 0 0 0-1.5H5.25Z" />
                        </svg>
                     </button>
                  </form>
                  <!-- FIM BUTTON PARA EDITAR  -->
               </div>
            </div>
         </div>
      <?php endforeach ?>
   </div>
</div>