<div class="ml-40 mr-40 mt-10 mb-10 border rounded-3xl p-8 shadow-lg">
   <form action=<?= route('artist.newArtwork') ?> class="space-y-4" method="POST" enctype="multipart/form-data" >
      <div>
         <label for="artwork_title" class="text-2xl font-bold block mb-1">Titulo da arte</label>
         <input
            id="artwork_title"
            name="artwork[title]"
            class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500"
            type="text"
            placeholder="Titulo da arte" 
            require/>
      </div>

      <div>
         
         <div class="relative">
            <label for="artwork_description" class="text-md text-bold block mb-1"><?= $description ?></label>
            <textarea
               id="artwork_description"
               name="artwork[description]"
               type="text"
               rows='6'
               cols='50'
               class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500"
               placeholder='Descrição da arte'></textarea>
         </div>
      </div>

      <div class="flex flex-col">
         <label for="artwork_image"
         >Selecione uma imagem:</label>
         <input type="file" id="artwork_image" name="image" accept="image/*" class="">
      </div>
      <div class="space-y-2">
         
      <div class="col-span-2 sm:col-span-1">
         <label for="category" class=" text-xl font-bold block mb-2 font-medium text-gray-900">Categoria</label>
         
         <select id="category" name="artwork[category_id]" class="bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 ">
            
            <option value="">Selecione a categoria</option> <?php foreach ($categories as $category) : ?>
                  <option value="<?= $category->id ?>"><?= $category->name ?></option>
            <?php endforeach ?>

         </select>
      </div>
            
      </div>
      <button
         type="submit"
         class="w-full bg-orange-500 hover:bg-orange-600 text-white py-2 rounded-md font-semibold transition">
         Publicar arte
      </button>
   </form>
</div>
