<div class="flex items-center justify-center">
    <div class="flex flex-col justify-center items-center max-w-[600px] ml-40 mr-40 mt-10 mb-10 border rounded-3xl p-8 shadow-lg">
        <div>
            <h1 class="text-3xl font-bold text-gray-900 block mb-1">Crie seu post</h1>
        </div>
        <form action=<?= route('artist.create') ?> class="space-y-4" method="POST" enctype="multipart/form-data">
            <div>
                <label for="artwork_title" class="text-xl font-bold block mb-1">Titulo</label>
                <input
                    id="artwork_title"
                    name="artwork[title]"
                    class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500"
                    type="text"
                    placeholder="Titulo da arte"
                    value="<?= $artwork->title ?>"
                    require />
            </div>
            <?php
            if ($artwork->errors('title')): ?>
                <p class="text-red-500 text-sm mt-1">
                    <?= $artwork->errors('title') ?>
                </p>
            <?php endif ?>

            <div>
                <div class="relative">
                    <label for="artwork_description" class="text-md text-bold block mb-1">Descrição</label>
                    <textarea
                        id="artwork_description"
                        name="artwork[description]"
                        type="text"
                        rows='6'
                        cols='50'
                        class="w-full px-3 py-2 border rounded-md border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500"
                        placeholder='Descrição da arte'><?= $artwork->description ?></textarea>
                </div>
            </div>
            <?php
            if ($artwork->errors('description')): ?>
                <p class="text-red-500 text-sm mt-1">
                    <?= $artwork->errors('description') ?>
                </p>
            <?php endif ?>

            <div class="max-h-[450px] overflow-hidden rounded-2xl shadow-lg">
                <img id="image_preview" src="<?= $artwork->image()->path() ?>" alt="arte"
                    class="object-cover rounded-2xl transition-transform duration-300 ease-in-out hover:scale-105 hover:shadow-xl cursor-pointer"
                    title="Clique para alterar a imagem" />
            </div>
            <button type="button" id="image_preview_submit" class="mt-2 w-full bg-blue-500 hover:bg-blue-600 text-white py-2 rounded-md font-semibold transition" style="display: none;">
                Confirmar Nova Imagem
            </button>
            <?php
            if ($artwork->errors('image_url')): ?>
                <p class="text-red-500 text-sm mt-1">
                    <?= $artwork->errors('image_url') ?>
                </p>
            <?php endif ?>
            <div class="flex flex-col">
                <label for="image_preview_input" class="sr-only">Selecione uma imagem:</label>
                <input type="file" id="image_preview_input" name="image" accept="image/*" class="">
            </div>
            <div class="space-y-2">

                <div class="col-span-2 sm:col-span-1">
                    <label for="category" class=" text-xl font-bold block mb-2 font-medium text-gray-900">Categoria</label>

                    <select id="category" name="artwork[category_id]" class="bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 ">

                        <option value="">Selecione a categoria</option>
                        <?php foreach ($categories as $category) : ?>
                            <option value="<?= $category->id ?>"><?= $category->name ?></option>
                        <?php endforeach ?>

                    </select>
                </div>
                <?php
                if ($artwork->errors('category_id')): ?>
                    <p class="text-red-500 text-sm mt-1">
                        <?= $artwork->errors('category_id') ?>
                    </p>
                <?php endif ?>
            </div>
            <button
                type="submit"
                class="w-full bg-orange-500 hover:bg-orange-600 text-white py-2 rounded-md font-semibold transition">
                Publicar post
            </button>
        </form>
    </div>
</div>
