<?php foreach (\Lib\FlashMessage::get() as $type => $msg): ?>
    <?php
    $bgColors = [
        'success' => 'bg-green-200 text-green-800 border-green-300',
        'danger'   => 'bg-red-200 text-red-800 border-red-300',
    ];

    $colorClass = $bgColors[$type] ?? 'bg-gray-100 text-gray-800 border-gray-300';
    ?>
    <div id="flashMessage" class="relative border-l-4 p-4 mb-4 w-96 rounded-md shadow-sm <?= $colorClass ?>">
        <div class="flex justify-between items-start">
            <svg xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                class="size-6 text-yellow-500">
                <path d="M5.85 3.5a.75.75 0 0 0-1.117-1 9.719 9.719 0 0 0-2.348 4.876.75.75 0 0 0 1.479.248A8.219 8.219 0 0 1 5.85 3.5ZM19.267 2.5a.75.75 0 1 0-1.118 1 8.22 8.22 0 0 1 1.987 4.124.75.75 0 0 0 1.48-.248A9.72 9.72 0 0 0 19.266 2.5Z" />
                <path fill-rule="evenodd" d="M12 2.25A6.75 6.75 0 0 0 5.25 9v.75a8.217 8.217 0 0 1-2.119 5.52.75.75 0 0 0 .298 1.206c1.544.57 3.16.99 4.831 1.243a3.75 3.75 0 1 0 7.48 0 24.583 24.583 0 0 0 4.83-1.244.75.75 0 0 0 .298-1.205 8.217 8.217 0 0 1-2.118-5.52V9A6.75 6.75 0 0 0 12 2.25ZM9.75 18c0-.034 0-.067.002-.1a25.05 25.05 0 0 0 4.496 0l.002.1a2.25 2.25 0 1 1-4.5 0Z" clip-rule="evenodd" />
            </svg>
            <div class="pr-4"><?= $msg ?></div>
            <button href="https://img.icons8.com/?size=100&id=gykZ2Zai2dlQ&format=png&color=000000" onclick="this.parentElement.parentElement.remove()" class="text-xl font-bold leading-none focus:outline-none">
                <img src="https://img.icons8.com/?size=100&id=gykZ2Zai2dlQ&format=png&color=000000" class="size-5" alt="close">
            </button>
        </div>

        <script>
            setTimeout(() => {
                const flash = document.getElementById('flashMessage');
                if (flash) {
                    flash.style.display = 'none';
                }
            }, 3000);
        </script>
    </div>
<?php endforeach; ?>