<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ArtHive</title>
    <script src="https://cdn.tailwindcss.com"></script>

    <link rel="stylesheet" href="/assets/css/application.css">
</head>

<body>
    <main class="container-fluid">

        <?php require '_flash_message.phtml'; ?>

        <header class="mb-3">
            <h1>
                <?= $title ?>
            </h1>
        </header>

        <?php require $view ?>

    </main>
</body>

</html>