<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
    tailwind.config = {
        theme: {
        extend: {
            fontFamily: {
            'inknut': ['"Inknut Antiqua"', 'serif'],
            }
        }
        }
    }
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@700&display=swap" rel="stylesheet">
</head>

<body class="h-screen bg-gray-900 flex items-center justify-center m-0 p-0 overflow-hidden">
    <div class="bg-transparent rounded-2xl shadow-xl w-[1100px] h-[700px] flex overflow-hidden">
        <div class="absolute top-4 left-1/2 transform -translate-x-1/2 z-50 w-full px-6">
            <?php require '_flash_message.phtml'; ?>
        </div>

        <div class="hidden md:block w-1/2 bg-gray-200">
            <img src="assets/images/loginImage.png" 
                alt="login image" 
                class="h-full w-full object-cover rounded-2xl" />
        </div>

        <div class="w-1/2 p-8 flex flex-col items-center justify-center bg-gray-200">
            <div class="mb-6 flex flex-col justify-center items-center">
                <h2 class="text-3xl font-bold text-indigo-900 font-inknut">LogIn</h2>
                <p class="text-sm text-indigo-900 font-semibold font-inknut">Welcome Back</p>
            </div>

            <?php require $view ?>

            <p class="text-xs text-center mt-4">
                Don’t have an account?
                <a href="#" class="text-blue-600 font-semibold">Create an account</a>
            </p>
        </div>
    </div>
</body>

</html>